apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: broker-service
  name: broker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: broker-service
    spec:
      containers:
        - name: broker-service
          image: nlmontes/broker-service:helm
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: CAMEL_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_USER
              value: "admin"
            - name: SPRING_ACTIVEMQ_PASSWORD
              value: "admin"
            - name: AMQ_USER
              valueFrom:
                secretKeyRef:
                  name: activemq-broker-secret
                  key: AMQ_USER
            - name: AMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq-broker-secret
                  key: AMQ_PASSWORD
          volumeMounts:
            - name: app-logs-volume
              mountPath: /logs
      restartPolicy: Always
      volumes:
        - name: app-logs-volume
          persistentVolumeClaim:
            claimName: broker-service-logs-pvc
