apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fraudcheck-system
  name: fraudcheck-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraudcheck-system
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fraudcheck-system
    spec:
      containers:
        - name: fraudcheck-system
          image: nlmontes/fraudcheck-system:helm
          imagePullPolicy: Always
          ports:
            - containerPort: 6060
          env:
            - name: CAMEL_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_USER
              value: "admin"
            - name: SPRING_ACTIVEMQ_PASSWORD
              value: "admin"
          volumeMounts:
            - name: app-logs-volume
              mountPath: /logs
      restartPolicy: Always
      volumes:
        - name: app-logs-volume
          persistentVolumeClaim:
            claimName: fraudcheck-system-logs-pvc
