apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-system
  labels:
    app: payment-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-system
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-system
    spec:
      containers:
        - name: payment-system
          image: nlmontes/payment-system:helm
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: CAMEL_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_USER
              value: "admin"
            - name: SPRING_ACTIVEMQ_PASSWORD
              value: "admin"
            - name: REDIS_HOST
              value: "redis-cache" # This matches your Redis service name
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: app-logs-volume
              mountPath: /logs
      restartPolicy: Always
      volumes:
        - name: app-logs-volume
          emptyDir: {}
