apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fraudcheck-system
  name: fraudcheck-system
spec:
  ports:
    - name: "6060"
      port: 6060
      targetPort: 6060
  selector:
    app: fraudcheck-system
status:
  loadBalancer: {}
