apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  selector:
    app: activemq
  ports:
    - name: web
      port: 8080 # Exposed as 8080 to other services
      targetPort: 8161 # Internally maps to 8161 inside the pod
      protocol: TCP
    - name: broker
      port: 61616
      targetPort: 61616
      protocol: TCP
  type: ClusterIP
