apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broker-service
  name: broker-service
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    app: broker-service
status:
  loadBalancer: {}
