apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-system1
  name: payment-system1
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 7070
  selector:
    app: payment-system1
status:
  loadBalancer: {}
